version: "3.8"

networks:
  application:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aggregator_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./.env:/app/.env
    depends_on:
      - db
    networks:
      - application
    entrypoint: ['/bin/sh', '-c']
    env_file:
      - .env
    command:
      - | 
        composer install 
        php artisan migrate --seed
        php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: innoscripta_news_db
      MYSQL_USER: innoscripta
      MYSQL_PASSWORD: secret
    networks:
      - application
    container_name: aggregator_db

